name: unify
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  curved_navigation_bar: ^0.3.7
  google_fonts: ^2.1.0
  table_calendar: ^3.0.0
  awesome_dialog: ^2.0.0
  flutter_svg: ^0.22.0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  firebase_database: ^6.1.2
  custom_switch: ^0.0.1
  lite_rolling_switch: ^0.1.1
  timeago: ^3.0.2
  intl: ^0.17.0
  image_picker: ^0.7.5+2
  firebase_storage: ^8.1.0
  flutter_icons: ^1.1.0
  flutter_verification_code: ^1.0.3
  mailer: ^5.0.0
  web_scraper: ^0.1.4
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  webview_flutter: ^2.0.7
  custom_refresh_indicator: ^0.9.0
  scrollable_positioned_list: ^0.1.10
  http: ^0.13.3
  toast: ^0.1.5
  firebase_messaging: ^10.0.0
  get: ^4.1.4
  flutter_slidable: ^0.6.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.4
  flutter_tindercard: ^0.2.0
  bubble: ^1.2.1
  confetti: ^0.5.5
  quiver: ^3.0.1
  full_screen_image: ^1.0.2
  cached_network_image: ^3.0.0
  share: ^2.0.1
  path_provider: ^2.0.1
  polls: ^1.0.1
  toggle_switch: ^0.1.9
  adaptive_theme: ^2.2.0
  modal_bottom_sheet: ^2.0.0
  smart_select: ^4.3.2
  agora_rtc_engine: ^4.0.1 # for video
  agora_rtm: ^0.9.11 # for chatting
  # wakelock: ^0.5.2
  # permission_handler: ^5.0.1+1
  stretchy_header: ^2.0.0
  carousel_slider: ^3.0.0
  video_player: ^2.1.1
  visibility_detector: ^0.2.0
  video_thumbnail: ^0.3.3
  shimmer: ^2.0.0
  percent_indicator: ^3.0.1
  flare_flutter: ^3.0.0
  chewie: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  custom_navigation_bar: ^0.8.1
  loading_indicator: ^2.0.1
  sticky_headers: ^0.2.0
  tabbar: ^0.1.1
  flutter_unicons: ^0.0.1
  animated_bottom_navigation_bar: ^0.3.2
  like_button: ^2.0.2
  flash: ^2.0.0
  # tmdb_dart: ^0.1.1
  # tmdb_api: ^1.2.5
  flip_card: ^0.5.0
  # integration_test: ^1.0.2+2
  flutter_dropdown: ^0.0.8
  page_transition: ^2.0.2
  material_design_icons_flutter: ^4.0.5955
  # simple_url_preview: ^2.0.0
  lazy_load_scrollview: ^1.3.0
  flutter_fadein: ^2.0.0
  line_icons: ^2.0.1
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # fonts:
  #   - family: AppIcons
  #     fonts:
  #       - asset: lib/Components/fonts/AppIcons.ttf
  #   - family: PingFang
  #     fonts:
  #       - asset: assets/fonts/PingFang-ExtraLight.ttf
  #         weight: 300
  #       - asset: assets/fonts/PingFang-Light.ttf
  #         weight: 400
  #       - asset: assets/fonts/PingFang-Regular.ttf
  #         weight: 500
  #       - asset: assets/fonts/PingFang-Medium.ttf
  #         weight: 600
  #       - asset: assets/fonts/PingFang-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/PingFang-Heavy.ttf
  #         weight: 800

  #   - family: H
  #     fonts:
  #       - asset: assets/fonts/Light.ttf
  #         weight: 500
  #       - asset: assets/fonts/Medium.ttf
  #         weight: 600
  #       - asset: assets/fonts/Bold.ttf
  #         weight: 700
  #   - family: Futura
  #     fonts:
  #       - asset: assets/fonts/Futura-Maxi-CG-Bold-Regular.ttf
  #         weight: 700
  #   - family: Futura1
  #     fonts:
  #       - asset: assets/fonts/Futura-Maxi-CG-Demi-Regular.ttf
  #         weight: 700
  #   - family: Futura2
  #     fonts:
  #       - asset: assets/fonts/Futura-Maxi-CG-Light-Regular.ttf
  #         weight: 700
  #   - family: Futura3
  #     fonts:
  #       - asset: assets/fonts/Futura-Maxi-CG-Book-Regular.ttf
  #         weight: 700
  #   - family: Book
  #     fonts:
  #       - asset: assets/fonts/Futura-Book.ttf
  #         weight: 700
  #   - family: Bold
  #     fonts:
  #       - asset: assets/fonts/Futura-Bold.ttf
  #         weight: 700
  #   - family: Medium
  #     fonts:
  #       - asset: assets/fonts/Futura-Medium.ttf
  #         weight: 700

  assets:
    - assets/images/
    - assets/icons/
    - assets/anim/like.flr
    - assets/anim/play_pause.flr
    - assets/anim/play.flr
    - assets/bg.mp4
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
